# Generated by Django 5.0.1 on 2024-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.JSONField(default=dict),
        ),
    ]
