# Generated by Django 5.0.1 on 2024-03-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_patient_address_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
