# Generated by Django 5.0.1 on 2024-03-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_patient_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
